(() => {
'use strict';
const $=s=>document.querySelector(s), cats=GUIDE_DATA.categories, KEY='arban-admin-draft-v1';
const copy=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let places=copy(GUIDE_DATA.places),selected=null,draft=null,dirty=false,showPreview=false;
try{const saved=window.ARBAN_CONNECTION?.admin ? null : JSON.parse(localStorage.getItem(KEY));if(saved?.version===1&&Array.isArray(saved.places)&&saved.places.every(p=>p&&typeof p.id==='string'&&cats.some(c=>c.id===p.category)))places=saved.places;}catch(e){$('#status').textContent='저장 내용을 읽지 못해 원본 정보를 표시합니다.';}
const specs=[['name','장소 이름','input',true],['subtitle','한 줄 소개','input'],['recommendation','캐릭터 말풍선','textarea'],['introduction','장소 설명','textarea'],['highlights','주요 메뉴 · 상품 · 즐길 거리','textarea'],['address','주소','input'],['hours','운영시간 · 정기휴무 (줄마다 입력)','textarea'],['distance','호텔에서 도보 시간','input'],['naverUrl','네이버 지도 링크','url'],['googleUrl','구글 지도 링크','url']];
function status(t){$('#status').textContent=t;}
function safeImage(s){if(/^https:\/\//.test(s||''))return s;return /^(\.\.\/image\/|\.\.\/places\/|assets\/|data:image\/(png|jpeg|webp);base64,)/.test(s||'')?s:'';}
function photosOf(p){return [{role:'listing',src:p.listingImage||p.image||''},{role:'hero',src:p.heroImage||p.image||'',label:p.imageLabel||'장소 사진'},...(p.extraPhotos||[]).map(x=>({role:'hero',src:x.src,label:x.label})),{role:'detail',src:p.detailImage||'',label:p.detailImageLabel||'추가 사진'}];}
function list(){const term=$('#search').value.trim(),cat=$('#filter').value;const found=places.filter(p=>(!cat||p.category===cat)&&p.name.includes(term));$('#count').textContent=`${found.length}곳`;$('#list').innerHTML=found.map(p=>`<button type="button" class="item ${p.id===selected?'active':''}" data-id="${esc(p.id)}">${esc(p.name)}<small>${esc(cats.find(c=>c.id===p.category)?.name)} · ${p.hidden?'숨김':'노출 예정'}</small></button>`).join('')||'<p>검색 결과가 없습니다.</p>';}
function mayLeave(){return !dirty||confirm('저장하지 않은 변경이 있어요. 변경을 버리고 이동할까요?');}
function open(id){$('#previewToggle').disabled=false;selected=id;draft=copy(places.find(p=>p.id===id));draft._photos=photosOf(draft);dirty=false;showPreview=false;$('#editor').hidden=false;$('#preview').hidden=true;$('#previewToggle').textContent='미리보기';$('#heading').textContent=draft.name;$('#fields').innerHTML=`<label>분류<select name="category">${cats.map(c=>`<option value="${c.id}" ${c.id===draft.category?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>노출 설정<select name="hidden"><option value="false" ${!draft.hidden?'selected':''}>노출</option><option value="true" ${draft.hidden?'selected':''}>숨김</option></select></label>`+specs.map(([key,label,type,required])=>`<label class="${type==='textarea'?'full':''}">${label}${required?' *':''}${type==='textarea'?`<textarea name="${key}">${esc(draft[key]||'')}</textarea>`:`<input name="${key}" type="${type==='url'?'url':'text'}" value="${esc(draft[key]||'')}" ${required?'required':''}>`}</label>`).join('');renderPhotos();list();status('편집 후 저장 버튼을 눌러주세요.');}
function collect(){for(const [key] of specs)draft[key]=$('#editor').elements[key].value.trim();draft.category=$('#editor').elements.category.value;draft.hidden=$('#editor').elements.hidden.value==='true';}
function renderPhotos(){$('#photos').innerHTML=draft._photos.map((p,i)=>`<div class="photo"><img src="${esc(safeImage(p.src))}" alt="사진 미리보기"><div><select aria-label="사진 ${i+1} 위치" data-role="${i}">${[['listing','장소 선택 목록'],['hero','상단 사진 · 위에서부터 표시'],['detail','상세 페이지 아래 사진']].map(([v,l])=>`<option value="${v}" ${p.role===v?'selected':''}>${l}</option>`).join('')}</select><input type="text" data-label="${i}" value="${esc(p.label||'')}" placeholder="사진 설명 (선택)" aria-label="사진 ${i+1} 설명"><input type="file" accept="image/png,image/jpeg,image/webp" data-upload="${i}" aria-label="사진 ${i+1} 교체"><div class="photo-controls"><button type="button" data-up="${i}" ${i===0?'disabled':''}>위로</button><button type="button" data-down="${i}" ${i===draft._photos.length-1?'disabled':''}>아래로</button><button type="button" data-delete="${i}">사진 제거</button></div></div></div>`).join('');$('#photos').querySelectorAll('img').forEach(im=>{im.onerror=()=>{im.hidden=true;};});}
function prepared(){collect();const p=copy(draft),photos=p._photos;const find=r=>photos.filter(x=>x.role===r&&x.src);if(find('listing').length>1||find('detail').length>1)throw Error('목록 사진과 아래 사진은 각각 한 장만 지정해 주세요.');if(find('hero').length>21)throw Error('상세 사진은 장소당 최대 21장까지 추가할 수 있어요.');p.listingImage=find('listing')[0]?.src||'';p.heroImage=find('hero')[0]?.src||'';p.image=p.heroImage;p.detailImage=find('detail')[0]?.src||'';p.detailImageLabel=find('detail')[0]?.label||p.detailImageLabel||'추가 사진';p.imageLabel=find('hero')[0]?.label||'장소 사진';p.extraPhotos=find('hero').slice(1).map(x=>({src:x.src,label:x.label||'장소 사진'}));delete p._photos;for(const k of ['naverUrl','googleUrl'])if(p[k]){let u;try{u=new URL(p[k]);}catch{throw Error('지도 링크를 확인해 주세요.');}if(!['https:','http:'].includes(u.protocol))throw Error('지도 링크는 http 또는 https 주소여야 합니다.');}return p;}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify({version:1,places:next}));return true;}catch{alert('저장 공간이 부족하거나 브라우저 저장이 차단되어 있어요. 사진 용량을 줄여주세요. 변경 내용은 현재 화면에 남아 있습니다.');return false;}}
function preview(){const p=prepared();$('#preview').innerHTML=`<p class="hint">관리자용 내용 미리보기 · 실제 손님 화면의 배치와는 차이가 있습니다.${p.hidden?' · 숨김 상태':''}</p><h2>${esc(p.name)}</h2><p>${esc(p.subtitle)}</p><div class="admin-photo-slides">${[p.heroImage,...p.extraPhotos.map(x=>x.src)].filter(Boolean).map(s=>`<img src="${esc(safeImage(s))}" alt="장소 사진">`).join('')}</div><p class="hint">사진을 옆으로 넘겨 순서를 확인하세요.</p><p class="bubble">${esc(p.recommendation)}</p><h3>장소 소개</h3><p>${esc(p.introduction)}</p><h3>${p.category==='food'||p.category==='cafe'?'주요 메뉴':p.category==='shopping'?'주요 상품':'즐길 거리'}</h3><p>${esc(p.highlights)}</p><dl>${[['주소',p.address],['운영시간',p.hours],['호텔에서',p.distance]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${p.naverUrl?`<a href="${esc(p.naverUrl)}" target="_blank" rel="noopener">네이버 지도 ↗</a>`:''}${p.googleUrl?`<a href="${esc(p.googleUrl)}" target="_blank" rel="noopener">구글 지도 ↗</a>`:''}${p.detailImage?`<p><img src="${esc(safeImage(p.detailImage))}" alt="추가 사진"></p>`:''}`;}
$('#filter').innerHTML+=cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
$('#search').oninput=list;$('#filter').onchange=list;
$('#list').onclick=e=>{const b=e.target.closest('[data-id]');if(b&&mayLeave())open(b.dataset.id);};
$('#editor').oninput=()=>{dirty=true;status('저장하지 않은 변경사항이 있습니다.');};
$('#photos').onchange=async e=>{const el=e.target;if(el.dataset.label!==undefined){draft._photos[+el.dataset.label].label=el.value.trim();dirty=true;}if(el.dataset.role!==undefined){draft._photos[+el.dataset.role].role=el.value;dirty=true;}if(el.dataset.upload!==undefined){const f=el.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2*1024*1024){alert('2MB 이하 JPG·PNG·WebP 사진을 선택해주세요.');el.value='';return;}const activeDraft=draft,photo=draft._photos[+el.dataset.upload];const reader=new FileReader();reader.onload=()=>{if(draft!==activeDraft||!draft._photos.includes(photo))return;photo.src=reader.result;dirty=true;renderPhotos();};reader.onerror=()=>alert('사진을 읽지 못했습니다.');reader.readAsDataURL(f);}};
$('#photos').onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=+(b.dataset.up??b.dataset.down??b.dataset.delete);if(b.dataset.delete!==undefined)draft._photos.splice(i,1);else{const j=i+(b.dataset.up!==undefined?-1:1);[draft._photos[i],draft._photos[j]]=[draft._photos[j],draft._photos[i]];}dirty=true;renderPhotos();};
$('#addPhoto').onclick=()=>{draft._photos.push({role:'hero',src:''});dirty=true;renderPhotos();};

$('#addPhotos').onchange=async event=>{
 const files=[...event.target.files],activeDraft=draft;
 event.target.value='';
 if(!files.length)return;
 if(files.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2*1024*1024)){alert('사진은 각각 2MB 이하의 JPG·PNG·WebP로 선택해주세요.');return;}
 if(draft._photos.filter(p=>p.role==='hero').length+files.length>21){alert('상세 사진은 장소당 최대 21장까지 추가할 수 있어요.');return;}
 event.target.disabled=true;
 try{
  const photos=await Promise.all(files.map(f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({role:'hero',src:r.result,label:''});r.onerror=()=>reject(Error('사진을 읽지 못했어요. 다시 선택해주세요.'));r.readAsDataURL(f);}))); 
  if(draft!==activeDraft)return;
  if(draft._photos.filter(p=>p.role==='hero').length+photos.length>21)throw Error('상세 사진은 최대 21장입니다. 사진 수를 줄여주세요.');
  draft._photos.push(...photos);dirty=true;renderPhotos();status(`${photos.length}장을 추가했어요. 순서를 확인한 뒤 저장해주세요.`);
 }catch(error){alert(error.message);}finally{event.target.disabled=false;}
};

$('#editor').onsubmit=e=>{e.preventDefault();try{const p=prepared();const next=places.map(x=>x.id===selected?p:x);if(persist(next)){places=next;dirty=false;list();$('#heading').textContent=p.name;status('이 브라우저에 저장했어요. 실제 사이트에는 아직 반영되지 않습니다.');}}catch(err){alert(err.message);}};
$('#previewToggle').onclick=()=>{try{if(!showPreview)preview();showPreview=!showPreview;$('#preview').hidden=!showPreview;$('#editor').hidden=showPreview;$('#previewToggle').textContent=showPreview?'편집으로 돌아가기':'미리보기';}catch(err){alert(err.message);}};
$('#revert').onclick=()=>{if(mayLeave())open(selected);};
$('#add').onclick=()=>{if(!mayLeave())return;const p={id:'new-'+Date.now(),name:'새 장소',category:$('#filter').value||'food',hidden:true};places.push(p);open(p.id);dirty=true;status('새 장소는 숨김으로 시작합니다. 내용을 입력하고 저장해주세요.');};
$('#remove').onclick=()=>{if(!confirm('이 장소를 작업용 수정본에서 삭제할까요? 실제 사이트에는 영향을 주지 않습니다.'))return;const next=places.filter(p=>p.id!==selected);if(persist(next)){places=next;dirty=false;if(places.length)open(places[0].id);else{location.reload();}}};
$('#export').onclick=()=>{if(dirty){alert('먼저 현재 장소를 저장해주세요.');return;}const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),places},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='arban-places-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('수정본을 내려받았어요. 이 파일을 GitHub에 올리는 것만으로는 사이트에 반영되지 않습니다.');};
window.ARBAN_ADMIN = { snapshot(){if(dirty)throw Error('먼저 현재 장소를 저장해주세요.');return copy(places);}, setPublished(next){places=copy(next);if(selected&&places.some(p=>p.id===selected))open(selected);list();} };
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(places.length)open(places[0].id);else{$('#editor').hidden=true;$('#previewToggle').disabled=true;list();}
})();